# Generated by Django 5.0.3 on 2024-03-21 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("nazev", models.CharField(max_length=25)),
                ("privilegie", models.CharField(max_length=255)),
                ("datum_vytvoreni", models.DateTimeField()),
                ("posledni_zmena", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StavUkolu",
            fields=[
                ("stav_ukolu_id", models.AutoField(primary_key=True, serialize=False)),
                ("nazev", models.CharField(max_length=25)),
                ("popis", models.CharField(max_length=255)),
                ("datum_vytvoreni", models.DateTimeField()),
                ("posledni_zmena", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TypProjektu",
            fields=[
                (
                    "typ_projektu_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nazev", models.CharField(max_length=25)),
                ("datum_vytvoreni", models.DateTimeField()),
                ("posledni_zmena", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projekt",
            fields=[
                ("projekt_id", models.AutoField(primary_key=True, serialize=False)),
                ("datum_vytvoreni", models.DateTimeField()),
                ("posledni_zmena", models.DateTimeField(blank=True, null=True)),
                (
                    "typ_projektu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="UkolnicekApp.typprojektu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Uzivatel",
            fields=[
                ("uzivatel_id", models.AutoField(primary_key=True, serialize=False)),
                ("uzivatelske_jmeno", models.CharField(max_length=25)),
                ("krestni_jmeno", models.CharField(max_length=25)),
                ("prijmeni", models.CharField(max_length=25)),
                ("heslo", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=50)),
                ("datum_vytvoreni", models.DateTimeField()),
                ("posledni_zmena", models.DateTimeField(blank=True, null=True)),
                ("posledni_login", models.DateTimeField(blank=True, null=True)),
                ("prihlasen", models.BooleanField()),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="UkolnicekApp.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ukol",
            fields=[
                ("ukol_id", models.AutoField(primary_key=True, serialize=False)),
                ("nazev", models.CharField(max_length=25)),
                ("popis", models.CharField(max_length=255)),
                ("priorita", models.IntegerField()),
                ("nejzazsi_termin", models.DateTimeField()),
                ("datum_vybrani", models.DateTimeField(blank=True, null=True)),
                ("datum_dokonceni", models.DateTimeField(blank=True, null=True)),
                ("predpo_cas", models.IntegerField()),
                ("datum_vytvoreni", models.DateTimeField()),
                ("posledni_zmena", models.DateTimeField(blank=True)),
                (
                    "projekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="UkolnicekApp.projekt",
                    ),
                ),
                (
                    "stav_ukolu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="UkolnicekApp.stavukolu",
                    ),
                ),
                (
                    "uzivatel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="UkolnicekApp.uzivatel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projekt",
            name="uzivatel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="UkolnicekApp.uzivatel",
            ),
        ),
        migrations.CreateModel(
            name="Pratelstvi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pritel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="followers",
                        to="UkolnicekApp.uzivatel",
                    ),
                ),
                (
                    "uzivatel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="following",
                        to="UkolnicekApp.uzivatel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorieUzivatelu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="UkolnicekApp.projekt",
                    ),
                ),
                (
                    "uzivatel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="UkolnicekApp.uzivatel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UzivatelProjekt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="UkolnicekApp.projekt",
                    ),
                ),
                (
                    "uzivatel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="UkolnicekApp.uzivatel",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="pratelstvi",
            constraint=models.UniqueConstraint(
                fields=("uzivatel", "pritel"), name="Pratelstvi_PK"
            ),
        ),
        migrations.AddConstraint(
            model_name="historieuzivatelu",
            constraint=models.UniqueConstraint(
                fields=("uzivatel", "projekt"), name="Historie_uzivatelu_PK"
            ),
        ),
        migrations.AddConstraint(
            model_name="uzivatelprojekt",
            constraint=models.UniqueConstraint(
                fields=("uzivatel", "projekt"), name="Uzivatel_Projektv1_PK"
            ),
        ),
    ]
